### ISSUE TITLE
Add tests and CI for this repo if possible

### ISSUE THREAD

**Issue by hsluoyz** [casbin-lua/lua-resty-casbin#3]
See: https://github.com/casbin-lua/lua-resty-casbin/pull/1#issuecomment-872995181

**Comment by hsluoyz** [comment]
@rushitote

**Comment by rushitote** [comment]
I think we can add them, I will give it a try.

**Comment by hsluoyz** [comment]
@rushitote next plz add the badges like:

![image](https://user-images.githubusercontent.com/3787410/124343476-4625f180-dbfe-11eb-9f01-1486b1a3ef33.png)
